---
title: "Group Assignment 3: A Bayesian Clustering Reanalysis of the French Short Boredom Proneness Scale"
format: pdf
author: "Nikola Sekulovski & Maarten Marsman"
editor: visual
---

# Information about the assignment

In this group assignment, you will **reanalyze an existing dataset** using the Bayesian graphical modeling methodology for clustering that you just learned. Again, you are provided with a short study description and a **specified Methods section**. Your task is to:

-   Complete the missing text in the Methods section.
-   Implement the analysis exactly as implied by the Methods section.
-   Write a very brief **Results section** where the results are summarized.

You will work with the **French subsample (N = 490)** from the original study, using **18 ordinal items** from the **Short Boredom Proneness Scale (SBPS)** and the **Curiosity and Exploration Inventory–II (CEI-II)**.

\newpage

# Introduction

Boredom proneness has been conceptualized as a trait-like tendency to experience boredom frequently and intensely, and has been linked to a broad range of psychological outcomes. The Short Boredom Proneness Scale (SBPS) was developed as a concise unidimensional measure of boredom proneness and has since been translated into multiple languages. In the original validation of the French version of the SBPS, Martarelli et al. (2022) examined the relationships between boredom proneness (SBPS), and measures on two subscales of the Curiosity and Exploration Inventory (CEI-II), using a regularized frequentist network approach. The authors expected to find three clusters corresponding to boredom, curiosity and exploration. However, using a post-hoc community detection approach, their analysis revealed two clusters: one comprising all SBPS items and another comprising all CEI-II items.

Recent work has increasingly adopted a network perspective, in which psychological constructs are modeled as systems of interacting components rather than as manifestations of latent variables. Within this framework, network the nodes are expected to cluster together according to the domains they belong to.

The aim of the present study is to reanalyze the French subsample of the original dataset using Bayesian graphical modeling and to inspect the evidence in favor of clustering. By adopting a Bayesian approach, we explicitly test the hypothesis of clustering and also estimate the cluster membership of the nodes.

# Method

## Data

The data consists of responses from N = 490 French-speaking participants ($M_{age} = 33.8$; 73% females and 27% males). The network includes 18 items, all measured on a 7-point Likert scale:

-   8 items from the Short Boredom Proneness Scale (SBPS)
-   10 items from the Curiosity and Exploration Inventory–II (CEI-II)

Missing data was handled by listwise deletion.

## Model Specification

To model conditional associations between items, we estimated a Bayesian Ordinal Markov Random Field (OMRF, Marsman et al., 2025). This model represents each item as a node in an undirected network, with edges encoding conditional dependence relationships between item pairs while controlling for all remaining variables in the network.

Bayesian model averaging was employed to integrate over uncertainty in network structure. As a result, inference was not based on a single network structure, but on the posterior distribution that takes into account the uncertainty with respect to both the partial association parameters and the structure of the network.

## Prior Distributions

### Structure Priors

In order to investigate the presence of clustering in the network, we apply the Stochastic Block model (SBM) as a prior on the network structure (Sekulovski et al., 2025). In the SBM model, the probability of an edge between two nodes depends on \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.

Based on the results from the previous study by Martarelli et al. (2022), we expect to find two clusters in the network structure, corresponding to the SBPS and CEI-II items. Therefore, we set the \_\_\_\_\_\_ hyperparameter to \_\_\_\_\_\_ reflect this prior belief.

Furthermore, we set the hyperparameters $\alpha_{within}$ and $\beta_{within}$ for the distribution of the within inclusion probability to \_\_\_\_\_ and $\alpha_{between}$ and $\beta_{between}$ for the distribution of the between inclusion probability to \_\_\_\_\_.

We retain all other hyperparameters at their default values as specified in Sekulovski et al. (2025)

### Parameter Priors

The partial association parameters were assigned independent Cauchy priors with a scale of 2.5.

## Inference

We calculate two cluster Bayes factors. In the first one we test the hypothesis of no clustering against the complement that the network exhibits more than one cluster. And in the second Bayes factor, we test the hypothesis of two clusters against the hypothesis of three clusters.

For the estimated cluster membership of the nodes, we report both the posterior mode and the posterior mean of the allocation vector.

## Software

We used the easybgm R package (Huth et al., 2024) to estimate the the model and plot the results. We ran the model using an adaptive Metropolis–Hastings algorithm, with all other sampling settings left at their default values.

# Results

```{r}
#| eval: false
#| warning: false
#| include: false
fit <- easybgm(data[, -c(1,2)], type = "ordinal", edge_prior = "Stochastic-Block", update_method = "adaptive-metropolis", beta_bernoulli_alpha = 1, beta_bernoulli_beta = 1, beta_bernoulli_alpha_between = 1, beta_bernoulli_beta_between =1, lambda = 1.59)

summary(fit)
clusterBayesfactor(fit, type = "point", b1 = 2, b2 = 3)
```

## Cluster Bayes factor tests

## Estimated Cluster Membership

## Prior Sensitivity Analysis

If time permits, re-run the analysis using a Beta-Bernoulli or Bernoullli structure priors. How do the results compare to those obtained using the SBM prior?

# References

-   Huth, K., Keetelaar, S., Sekulovski, N., van den Bergh, D., & Marsman, M. (2024). Simplifying Bayesian analysis of graphical models for the social sciences with easybgm: A user-friendly R-package. *advances.in/psychology, e66366* doi: 10.56296/aip00010

-   Martarelli, C. S., Baillifard, A., & Audrin, C. (2022). A trait-based network perspective on the validation of the french short boredom proneness scale. *European Journal of Psychological Assessment, 39,* 390–399 doi: 10.1027/1015-5759/a000718346

-   Marsman, M., van den Bergh, D., & Haslbeck, J. M. B. (2025). Bayesian analysis of the ordinal Markov random field. *Psychometrika, 90* , 146–182. doi: 10.1017/psy.2024.4

-   Sekulovski, N., Arena, G., Haslbeck, J., Huth, K., Friel, N., & Marsman, M. (2024). A Stochastic Block Prior for Clustering in Graphical Models. Preprint. doi: 10.31234/osf.io/29p3m_v4
