---
title: "Group Assignment 1: A Bayesian Reanalysis of the French Short Boredom Proneness Scale"
format: pdf
author: "Nikola Sekulovski & Maarten Marsman"
editor: visual
---

# Information about the assignment

In this group assignment, you will **reanalyze an existing dataset** using the Bayesian graphical modeling methodology that you just learned. You are provided with a short study description and a **specified Methods section**. Your task is to:

-   Complete the definition of the inclusion Bayes factor in the Methods section
-   Implement the analysis exactly as implied by the Methods section
-   Write a very brief **Results section** where the results are summarized.

You will work with the **French subsample (N = 490)** from the original study, using **18 ordinal items** from the **Short Boredom Proneness Scale (SBPS)** and the **Curiosity and Exploration Inventory–II (CEI-II)**.

```{r}
#| eval: false
#| warning: false
#| include: false
data <- read_csv("N0271_1_raw data.csv")
data_filtered <- data %>%
   filter(sample == "fr") %>%
    select(starts_with("A"), starts_with("G"), starts_with("S"), starts_with("C")) %>%
    select(-SBPS_IMC_6, -CEIII_IMC7, -sample)

saveRDS(data_filtered, "data_group_assignment.rds")



# rename the second variable to Gender
colnames(data_filtered)[2] <- "Gender"

data_filtered$Gender <- as.factor(data_filtered$Gender)

summary(data_filtered)

# check if there is NAs in the data
sum(is.na(data_filtered))
```

\newpage

# Introduction

Boredom proneness has been conceptualized as a trait-like tendency to experience boredom frequently and intensely, and has been linked to a broad range of psychological outcomes. The Short Boredom Proneness Scale (SBPS) was developed as a concise unidimensional measure of boredom proneness and has since been translated into multiple languages. In the original validation of the French version of the SBPS, Martarelli et al. (2022) examined the relationships between boredom proneness (SBPS), and measures on two subcales of the Curiosity and Exploration Inventory (CEI-II), using a regularized frequentist network approach. Their analysis suggested positive associations between boredom and curiosity items and negative associations between boredom and exploration items.

Recent work has increasingly adopted a network perspective, in which psychological constructs are modeled as systems of interacting components rather than as manifestations of latent variables. Within this framework, network models offer a flexible way to examine conditional associations between individual questionnaire items while controlling for all other variables in the system.

The aim of the present study is to reanalyze the French subsample of the original dataset using Bayesian graphical modeling. By adopting a Bayesian approach, we explicitly quantify uncertainty in network structure and parameters, and we distinguish between absence of evidence and evidence of absence for network edges. In particular, we estimate a Bayesian ordinal network model that directly takes into account the ordinal measurement level of the variables.

# Method

## Data

The data consists of responses from N = 490 French-speaking participants ($M_{age} = 33.8$; 73% females and 27% males). The network includes 18 items, all measured on a 7-point Likert scale:

-   8 items from the Short Boredom Proneness Scale (SBPS)
-   10 items from the Curiosity and Exploration Inventory–II (CEI-II)

Missing data was handled by listwise deletion.

## Model Specification

To model conditional associations between items, we estimated a Bayesian Ordinal Markov Random Field (OMRF, Marsman et al., 2025). This model represents each item as a node in an undirected network, with edges encoding conditional dependence relationships between item pairs while controlling for all remaining variables in the network.

Bayesian model averaging was employed to integrate over uncertainty in network structure. As a result, inference was not based on a single network structure, but on the posterior distribution that takes into account the uncertainty with respect to both the partial association parameters and the structure of the network.

## Prior Distributions

### Structure Priors

The edges were assigned independent Bernoulli priors. We expected the structure to be dense (i.e., many connections between the nodes), therefore we set the inclusion probability for the Bernoulli structure prior to $0.7$. To assess the sensitivity of the results to this assumption, we repeated the analysis by setting the inclusion probability to $0.3$.

### Parameter Priors

The partial association parameters were assigned independent Cauchy priors with a scale of 2.5.

## Inference

Evidence for the presence or absence of edges was quantified using the inclusion Bays factor. The inclusion Bayes factor \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_. These Bayes factors were used to classify edges as showing evidence for \_\_\_\_\_\_, evidence for \_\_\_\_\_\_, or \_\_\_\_\_\_ evidence.

\_\_\_\_\_\_ plots were used to visualize which edges fall into each of these categories. In this study, an inclusion Bayes factor of \_\_\_\_\_\_ was used as the threshold for strong evidence for inclusion, and a Bayes factor of \_\_\_\_\_\_ was used as the threshold for strong evidence for exclusion; values falling between these thresholds were classified as inconclusive.

Posterior summaries of edge parameters were obtained from the model-averaged posterior distribution from which posterior mean and HDI intervals were calculated. Centrality measures were not estimated or interpreted.

## Software

We used the easybgm R package (Huth et al., 2024) to estimate the the model and plot the results.

# Results

## Network Estimation

This section should report general characteristics of the estimated network, including the number of edges for which there was conclusive evidence, the number of possible edges, and an overall description of the estimated network structure.

## Edge Evidence

This section should describe the results of the Bayes factor analysis at the edge level. Report the edge evidence plot. Particular attention should be paid to patterns of associations within and between the SBPS and CEI-II items. Edge evidence plots or summary tables should be referenced here.

## Edge Parameter Estimates

This section should summarize the estimated edge parameters. Describe the estimated network structure. Provide uncertainty estimates.

## Prior Sensitivity Analysis

This section should compare the primary analysis to the analysis with the alternative prior specification.

# References

-   Huth, K., Keetelaar, S., Sekulovski, N., van den Bergh, D., & Marsman, M. (2024). Simplifying Bayesian analysis of graphical models for the social sciences with easybgm: A user-friendly R-package. *advances.in/psychology, e66366* doi: 10.56296/aip00010

-   Martarelli, C. S., Baillifard, A., & Audrin, C. (2022). A trait-based network perspective on the validation of the french short boredom proneness scale. *European Journal of Psychological Assessment, 39,* 390–399 doi: 10.1027/1015-5759/a000718346

-   Marsman, M., van den Bergh, D., & Haslbeck, J. M. B. (2025). Bayesian analysis of the ordinal Markov random field. *Psychometrika, 90* , 146–182. doi: 10.1017/psy.2024.4
